import { useState } from "react";

// ============================================================
// FIND demo prototype. One seeded scenario, four beats, one flow.
// Live Claude calls power the Experience Alchemist, Zuri, the SOW,
// and the agent re-derivation. EESG numbers are computed in the
// browser from visible inputs, never generated by the model.
// ============================================================

const T = {
  ink: "#0E1620",
  panel: "#152230",
  panelLite: "#1C2E40",
  line: "#28394C",
  gold: "#E8B85C",   // verification and value
  teal: "#3FD0C9",   // Telos reasoning
  text: "#EEF3F8",
  muted: "#93A4B5",
  shock: "#E8845C",  // currency shock
};

const FONTS = `
@import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap');
* { box-sizing: border-box; }
@keyframes spin { to { transform: rotate(360deg); } }
@keyframes rise { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }
.rise { animation: rise .45s ease both; }
`;

// ---- seeded scenario (labeled as demo data on screen) ----
const SEED = {
  builder: {
    name: "Adaeze Okonkwo",
    role: "Backend engineer",
    city: "Lagos, Nigeria",
    raw:
      "i have been building stuff for like 4 years. mostly python and django. " +
      "worked on a payment app for a fintech here in lagos, handled the part that " +
      "reconciles transactions and catches mismatches. also did some postgres tuning " +
      "when things got slow, and i set up the queue system so payments dont get lost " +
      "when the network drops. helped 2 junior devs learn the codebase.",
  },
  employer: {
    name: "Nordwind Pay",
    city: "Berlin, Germany",
    need: "Backend engineer for a payments reconciliation service",
  },
  economics: {
    grossUsd: 4500,
    ngnBefore: 1550,     // illustrative rate, seeded
    ngnAfter: 1820,      // post-shock illustrative rate, seeded
    retention: 0.62,     // share of earnings retained in local economy, assumption
  },
};

// ---- live Claude call helper ----
async function callClaude(system, userText, expectJson) {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      model: "claude-sonnet-4-6",
      max_tokens: 1000,
      system,
      messages: [{ role: "user", content: userText }],
    }),
  });
  const data = await res.json();
  const text = (data.content || [])
    .filter((b) => b.type === "text")
    .map((b) => b.text)
    .join("\n")
    .trim();
  if (!expectJson) return text;
  const clean = text.replace(/```json/g, "").replace(/```/g, "").trim();
  return JSON.parse(clean);
}

// ---- small shared pieces ----
function Cooper({ note }) {
  return (
    <div style={{
      display: "inline-flex", alignItems: "center", gap: 8,
      fontFamily: "'JetBrains Mono', monospace", fontSize: 11,
      color: T.muted, border: `1px solid ${T.line}`, borderRadius: 4,
      padding: "4px 9px", letterSpacing: 0.3,
    }}>
      <span style={{ color: T.teal }}>cooper</span>
      <span>{note}</span>
    </div>
  );
}

function Spinner({ label }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 10, color: T.muted, fontSize: 14 }}>
      <span style={{
        width: 14, height: 14, border: `2px solid ${T.line}`,
        borderTopColor: T.teal, borderRadius: "50%",
        display: "inline-block", animation: "spin .8s linear infinite",
      }} />
      {label}
    </div>
  );
}

function Btn({ children, onClick, disabled, kind }) {
  const styles = {
    primary: { background: T.gold, color: T.ink, border: "none" },
    ghost: { background: "transparent", color: T.text, border: `1px solid ${T.line}` },
    shock: { background: "transparent", color: T.shock, border: `1px solid ${T.shock}` },
  }[kind || "primary"];
  return (
    <button onClick={onClick} disabled={disabled} style={{
      ...styles, fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600,
      fontSize: 14, padding: "11px 18px", borderRadius: 7, cursor: disabled ? "default" : "pointer",
      opacity: disabled ? 0.5 : 1, transition: "opacity .2s",
    }}>
      {children}
    </button>
  );
}

function Panel({ children, accent }) {
  return (
    <div className="rise" style={{
      background: T.panel, border: `1px solid ${accent || T.line}`,
      borderRadius: 12, padding: 22,
    }}>{children}</div>
  );
}

function ErrLine({ msg, onRetry }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 12, color: T.shock, fontSize: 14 }}>
      <span>The model did not respond. Check the connection and run it again.</span>
      <Btn kind="ghost" onClick={onRetry}>Run again</Btn>
    </div>
  );
}

const ngn = (n) => "NGN " + Math.round(n).toLocaleString("en-US");

// ============================================================
// BEAT 1: Candidate. Experience Alchemist (live)
// ============================================================
function Candidate({ onDone }) {
  const [raw, setRaw] = useState(SEED.builder.raw);
  const [out, setOut] = useState(null);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState(false);

  async function run() {
    setBusy(true); setErr(false); setOut(null);
    try {
      const sys =
        "You are the Experience Alchemist inside FIND. You convert a builder's informal, " +
        "messy account of their work into recruiter-ready, outcome-led claims. You never invent " +
        "facts that are not present or directly implied. Return ONLY valid JSON, no preamble, no " +
        "markdown fences. Shape: {\"role\":string, \"headline\":string, \"outcomes\":[{\"statement\":string," +
        "\"basis\":string}], \"skills\":[string], \"integrity_note\":string}. Each outcome.statement is one " +
        "crisp business-outcome line. Each basis names the part of the raw text it came from. " +
        "integrity_note states plainly what was claimed and what was not, so a recruiter trusts it.";
      const result = await callClaude(sys, "Raw account:\n" + raw, true);
      setOut(result);
    } catch (e) { setErr(true); }
    setBusy(false);
  }

  return (
    <div style={{ display: "grid", gap: 18 }}>
      <Header
        eyebrow="Beat 1 of 4 . Builder"
        title="Turn real work into claims a recruiter trusts"
        sub="The builder writes how they actually talk. Telos transmutes it into verified outcomes, and marks what it will not claim."
      />
      <Cooper note="goal-directed: the builder's goal is recognition, not filling a form" />

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>
        <Panel>
          <Label>What the builder wrote</Label>
          <textarea
            value={raw}
            onChange={(e) => setRaw(e.target.value)}
            rows={9}
            style={{
              width: "100%", marginTop: 10, background: T.ink, color: T.text,
              border: `1px solid ${T.line}`, borderRadius: 8, padding: 12,
              fontFamily: "'Inter', sans-serif", fontSize: 14, lineHeight: 1.5, resize: "vertical",
            }}
          />
          <div style={{ marginTop: 14 }}>
            {busy ? <Spinner label="Telos is auditing the account for truth..." />
              : <Btn onClick={run}>Run the Experience Alchemist</Btn>}
          </div>
          {err && <div style={{ marginTop: 12 }}><ErrLine onRetry={run} /></div>}
        </Panel>

        <Panel accent={out ? T.gold : T.line}>
          <Label>Verified profile</Label>
          {!out && !busy && (
            <Empty msg="Run the Alchemist to see the messy account become recruiter-ready outcomes." />
          )}
          {busy && <div style={{ marginTop: 14 }}><Spinner label="Composing outcomes..." /></div>}
          {out && (
            <div className="rise" style={{ marginTop: 10, display: "grid", gap: 14 }}>
              <div>
                <div style={{ fontFamily: "'Space Grotesk'", fontWeight: 700, fontSize: 18, color: T.text }}>
                  {out.headline}
                </div>
                <div style={{ color: T.teal, fontSize: 13, marginTop: 2 }}>{out.role}</div>
              </div>
              <div style={{ display: "grid", gap: 10 }}>
                {(out.outcomes || []).map((o, i) => (
                  <div key={i} style={{ borderLeft: `2px solid ${T.gold}`, paddingLeft: 12 }}>
                    <div style={{ color: T.text, fontSize: 14, fontWeight: 500 }}>{o.statement}</div>
                    <div style={{ color: T.muted, fontSize: 12, marginTop: 3 }}>basis: {o.basis}</div>
                  </div>
                ))}
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: 7 }}>
                {(out.skills || []).map((s, i) => (
                  <span key={i} style={{
                    fontFamily: "'JetBrains Mono'", fontSize: 12, color: T.teal,
                    border: `1px solid ${T.line}`, borderRadius: 4, padding: "3px 8px",
                  }}>{s}</span>
                ))}
              </div>
              {out.integrity_note && (
                <div style={{
                  background: T.ink, border: `1px solid ${T.line}`, borderRadius: 8,
                  padding: 12, fontSize: 13, color: T.muted,
                }}>
                  <span style={{ color: T.gold, fontWeight: 600 }}>Integrity. </span>
                  {out.integrity_note}
                </div>
              )}
            </div>
          )}
        </Panel>
      </div>

      {out && <Continue label="See why this builder matches an employer" onClick={onDone} />}
    </div>
  );
}

// ============================================================
// BEAT 2: Match and Zuri (seeded score, live narration)
// ============================================================
const FACTORS = [
  { label: "Verified payment-reconciliation commits", weight: 0.34 },
  { label: "Distributed systems and queue depth", weight: 0.28 },
  { label: "Async and language fit with Berlin team", weight: 0.20 },
  { label: "Network-resilient delivery patterns", weight: 0.18 },
];

function Match({ onDone }) {
  const [zuri, setZuri] = useState("");
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState(false);

  async function ask() {
    setBusy(true); setErr(false); setZuri("");
    try {
      const sys =
        "You are Zuri, the reasoning voice of Telos inside FIND. You explain, in four to six " +
        "plain sentences, the causal chain behind a talent match. You speak with calm authority, " +
        "no hype, no em dashes. You reference the named match factors and connect them to the " +
        "employer's stated need. You make the logic feel inspectable, not magical.";
      const ctx =
        `Builder: ${SEED.builder.name}, ${SEED.builder.role}, ${SEED.builder.city}.\n` +
        `Employer need: ${SEED.employer.name}, ${SEED.employer.need}.\n` +
        `Match factors and weights: ${FACTORS.map((f) => `${f.label} (${f.weight})`).join("; ")}.\n` +
        `Seeded causal confidence: 0.91.`;
      const text = await callClaude(sys, ctx, false);
      setZuri(text);
    } catch (e) { setErr(true); }
    setBusy(false);
  }

  return (
    <div style={{ display: "grid", gap: 18 }}>
      <Header
        eyebrow="Beat 2 of 4 . Telos match"
        title="The match is a chain of reasons, not a keyword hit"
        sub="Telos scores the fit across causal factors. Zuri narrates the logic on demand, so the match can be questioned and trusted."
      />
      <Cooper note="progressive disclosure: the reasoning appears when asked, not all at once" />

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1.1fr", gap: 16 }}>
        <Panel>
          <Label>Causal confidence</Label>
          <div style={{ display: "flex", alignItems: "baseline", gap: 10, marginTop: 8 }}>
            <span style={{ fontFamily: "'Space Grotesk'", fontWeight: 700, fontSize: 46, color: T.gold }}>91%</span>
            <span style={{
              fontFamily: "'JetBrains Mono'", fontSize: 11, color: T.muted,
              border: `1px solid ${T.line}`, borderRadius: 4, padding: "2px 7px",
            }}>seeded for demo</span>
          </div>
          <div style={{ marginTop: 18, display: "grid", gap: 12 }}>
            {FACTORS.map((f, i) => (
              <div key={i}>
                <div style={{ display: "flex", justifyContent: "space-between", fontSize: 13, color: T.text }}>
                  <span>{f.label}</span>
                  <span style={{ color: T.muted, fontFamily: "'JetBrains Mono'" }}>{f.weight.toFixed(2)}</span>
                </div>
                <div style={{ height: 6, background: T.ink, borderRadius: 3, marginTop: 5 }}>
                  <div style={{ height: "100%", width: `${f.weight * 100 / 0.34}%`, background: T.teal, borderRadius: 3 }} />
                </div>
              </div>
            ))}
          </div>
        </Panel>

        <Panel accent={zuri ? T.teal : T.line}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <Label>Zuri explains the match</Label>
            <span style={{
              fontFamily: "'JetBrains Mono'", fontSize: 11, color: T.teal,
              border: `1px solid ${T.line}`, borderRadius: 4, padding: "2px 8px",
            }}>reasoning agent</span>
          </div>
          {!zuri && !busy && (
            <div style={{ marginTop: 16 }}>
              <Empty msg="Ask Zuri to walk the causal chain from the builder's evidence to the employer's need." />
              <div style={{ marginTop: 14 }}><Btn kind="ghost" onClick={ask}>Ask Zuri why this fits</Btn></div>
            </div>
          )}
          {busy && <div style={{ marginTop: 16 }}><Spinner label="Zuri is tracing the causal chain..." /></div>}
          {err && <div style={{ marginTop: 14 }}><ErrLine onRetry={ask} /></div>}
          {zuri && (
            <p className="rise" style={{ marginTop: 14, fontSize: 15, lineHeight: 1.65, color: T.text }}>
              {zuri}
            </p>
          )}
        </Panel>
      </div>

      {zuri && <Continue label="Open the employer view" onClick={onDone} />}
    </div>
  );
}

// ============================================================
// BEAT 3: Employer. PII-masked profile + live SOW
// ============================================================
function Employer({ onDone }) {
  const [sow, setSow] = useState(null);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState(false);

  async function gen() {
    setBusy(true); setErr(false); setSow(null);
    try {
      const sys =
        "You are the FIND procurement engine acting as Employer of Record. You draft a concise " +
        "Statement of Work for an enterprise client engaging a vetted builder through FIND. FIND is " +
        "the legal EOR and handles IP assignment and local tax remittance. Return ONLY valid JSON, no " +
        "fences. Shape: {\"title\":string,\"scope\":[string],\"deliverables\":[string],\"ip_clause\":string," +
        "\"eor_note\":string,\"term\":string}. Keep each line tight and concrete. No em dashes.";
      const ctx =
        `Client: ${SEED.employer.name}, ${SEED.employer.city}.\n` +
        `Need: ${SEED.employer.need}.\n` +
        `Builder profile is masked: a vetted backend engineer with verified payment-reconciliation ` +
        `and queue-resilience work. Monthly engagement at USD ${SEED.economics.grossUsd}.`;
      const result = await callClaude(sys, ctx, true);
      setSow(result);
    } catch (e) { setErr(true); }
    setBusy(false);
  }

  return (
    <div style={{ display: "grid", gap: 18 }}>
      <Header
        eyebrow="Beat 3 of 4 . Enterprise partner"
        title="A decision-ready match, with identity shielded"
        sub="The employer sees verified capability, not a name or a photo. Bias has nothing to grip. The Statement of Work drafts itself."
      />
      <Cooper note="eliminate excise: the employer decides on evidence, with no manual screening" />

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1.2fr", gap: 16 }}>
        <Panel>
          <Label>Masked builder profile</Label>
          <div style={{ marginTop: 14, display: "flex", alignItems: "center", gap: 12 }}>
            <div style={{
              width: 46, height: 46, borderRadius: 10, background: T.panelLite,
              border: `1px solid ${T.line}`, display: "flex", alignItems: "center",
              justifyContent: "center", color: T.muted, fontFamily: "'JetBrains Mono'", fontSize: 18,
            }}>FB</div>
            <div>
              <div style={{ color: T.text, fontWeight: 600 }}>FIND builder 0xA7</div>
              <div style={{ color: T.muted, fontSize: 13 }}>Backend engineer . identity shielded</div>
            </div>
          </div>
          <div style={{ marginTop: 16, display: "grid", gap: 8 }}>
            {["Verified payment-reconciliation delivery", "Queue resilience under network loss", "PostgreSQL performance tuning", "Mentored two junior engineers"].map((c, i) => (
              <div key={i} style={{ display: "flex", gap: 8, alignItems: "center", fontSize: 14, color: T.text }}>
                <span style={{ color: T.gold }}>verified</span>
                <span style={{ color: T.muted }}>{c}</span>
              </div>
            ))}
          </div>
          <div style={{
            marginTop: 16, background: T.ink, border: `1px solid ${T.line}`,
            borderRadius: 8, padding: 11, fontSize: 12.5, color: T.muted,
          }}>
            Name, location, photo, and gender are withheld until the employer commits. Telos shows
            capability first so the decision rests on evidence.
          </div>
        </Panel>

        <Panel accent={sow ? T.gold : T.line}>
          <Label>Statement of Work</Label>
          {!sow && !busy && (
            <div style={{ marginTop: 16 }}>
              <Empty msg="Generate the Statement of Work. FIND signs it as the Employer of Record." />
              <div style={{ marginTop: 14 }}><Btn onClick={gen}>Draft the Statement of Work</Btn></div>
            </div>
          )}
          {busy && <div style={{ marginTop: 16 }}><Spinner label="Compliance Agent is drafting the SOW..." /></div>}
          {err && <div style={{ marginTop: 14 }}><ErrLine onRetry={gen} /></div>}
          {sow && (
            <div className="rise" style={{ marginTop: 12, display: "grid", gap: 13 }}>
              <div style={{ fontFamily: "'Space Grotesk'", fontWeight: 700, fontSize: 17, color: T.text }}>{sow.title}</div>
              <SowList label="Scope" items={sow.scope} />
              <SowList label="Deliverables" items={sow.deliverables} />
              <div style={{ display: "grid", gap: 8 }}>
                <MiniNote label="IP assignment" body={sow.ip_clause} />
                <MiniNote label="Employer of Record" body={sow.eor_note} />
                <MiniNote label="Term" body={sow.term} />
              </div>
            </div>
          )}
        </Panel>
      </div>

      {sow && <Continue label="See the impact this placement creates" onClick={onDone} />}
    </div>
  );
}

function SowList({ label, items }) {
  return (
    <div>
      <div style={{ color: T.teal, fontSize: 12, fontFamily: "'JetBrains Mono'", marginBottom: 6 }}>{label}</div>
      <div style={{ display: "grid", gap: 6 }}>
        {(items || []).map((it, i) => (
          <div key={i} style={{ fontSize: 14, color: T.text, display: "flex", gap: 8 }}>
            <span style={{ color: T.gold }}>.</span><span>{it}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
function MiniNote({ label, body }) {
  return (
    <div style={{ background: T.ink, border: `1px solid ${T.line}`, borderRadius: 8, padding: 11 }}>
      <span style={{ color: T.gold, fontSize: 12, fontWeight: 600 }}>{label}. </span>
      <span style={{ color: T.muted, fontSize: 13 }}>{body}</span>
    </div>
  );
}

// ============================================================
// BEAT 4: EESG impact. Computed math + live agent re-derivation
// ============================================================
function Impact() {
  const e = SEED.economics;
  const [shocked, setShocked] = useState(false);
  const [agents, setAgents] = useState("");
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState(false);

  const rate = shocked ? e.ngnAfter : e.ngnBefore;
  const grossNgn = e.grossUsd * rate;
  const retainedNgn = grossNgn * e.retention;

  async function shock() {
    setShocked(true); setBusy(true); setErr(false); setAgents("");
    try {
      const sys =
        "You are two FIND agents reporting together: the Economics Agent and the Compliance Agent. " +
        "A currency move just changed the local exchange rate. In two short labeled paragraphs, one " +
        "from each agent, explain the response. Economics Agent: propose a purchasing-power patch so " +
        "the builder's local value holds. Compliance Agent: note that local tax remittance recomputes " +
        "at the new rate under the Employer of Record duty. Plain, precise, no hype, no em dashes. " +
        "Do not invent specific tax rates. Label each paragraph with the agent name.";
      const ctx =
        `Rate before: 1 USD = ${e.ngnBefore} NGN. Rate after: 1 USD = ${e.ngnAfter} NGN.\n` +
        `Monthly engagement: USD ${e.grossUsd}.\n` +
        `Local retention assumption: ${Math.round(e.retention * 100)} percent.\n` +
        `Retained local capital moved from ${Math.round(e.grossUsd * e.ngnBefore * e.retention)} ` +
        `to ${Math.round(e.grossUsd * e.ngnAfter * e.retention)} NGN nominal.`;
      const text = await callClaude(sys, ctx, false);
      setAgents(text);
    } catch (er) { setErr(true); }
    setBusy(false);
  }

  function reset() { setShocked(false); setAgents(""); setErr(false); }

  return (
    <div style={{ display: "grid", gap: 18 }}>
      <Header
        eyebrow="Beat 4 of 4 . Global Impact Commons, powered by Lexington Advisory"
        title="Every impact number shows its own derivation"
        sub="The SROI ledger does not assert a headline. It shows the inputs and the formula, then lets the math speak. Trigger a currency move and watch two agents re-derive it live."
      />
      <Cooper note="integrity: a figure you can inspect beats a figure you must believe" />

      <div style={{ display: "grid", gridTemplateColumns: "1.1fr 1fr", gap: 16 }}>
        <Panel accent={shocked ? T.shock : T.gold}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <Label>SROI derivation</Label>
            <span style={{
              fontFamily: "'JetBrains Mono'", fontSize: 11,
              color: shocked ? T.shock : T.muted,
              border: `1px solid ${shocked ? T.shock : T.line}`, borderRadius: 4, padding: "2px 8px",
            }}>{shocked ? "after currency move" : "baseline"}</span>
          </div>

          <div style={{ marginTop: 14, display: "grid", gap: 1, background: T.line, border: `1px solid ${T.line}`, borderRadius: 8, overflow: "hidden" }}>
            <Row k="Monthly engagement" v={`USD ${e.grossUsd.toLocaleString()}`} />
            <Row k="Exchange rate (illustrative)" v={`1 USD = ${rate.toLocaleString()} NGN`} hot={shocked} />
            <Row k="Gross, local currency" v={ngn(grossNgn)} sub={`${e.grossUsd.toLocaleString()} x ${rate.toLocaleString()}`} hot={shocked} />
            <Row k="Local retention assumption" v={`${Math.round(e.retention * 100)} percent`} />
            <Row k="Capital retained locally" v={ngn(retainedNgn)} sub={`${ngn(grossNgn)} x ${e.retention}`} accent hot={shocked} />
          </div>

          <div style={{ marginTop: 14, display: "flex", gap: 10 }}>
            {!shocked
              ? <Btn kind="shock" onClick={shock}>Trigger a currency move</Btn>
              : <Btn kind="ghost" onClick={reset}>Reset to baseline</Btn>}
          </div>

          <div style={{ marginTop: 14, display: "flex", gap: 7, flexWrap: "wrap" }}>
            {["SDG 8 decent work", "SDG 9 industry and innovation", "SDG 17 partnerships"].map((s, i) => (
              <span key={i} style={{
                fontFamily: "'JetBrains Mono'", fontSize: 11.5, color: T.teal,
                border: `1px solid ${T.line}`, borderRadius: 4, padding: "3px 8px",
              }}>{s}</span>
            ))}
          </div>
        </Panel>

        <Panel accent={agents ? T.teal : T.line}>
          <Label>Agents re-derive the value</Label>
          {!shocked && (
            <div style={{ marginTop: 16 }}>
              <Empty msg="Trigger the currency move on the left. The Economics Agent and the Compliance Agent respond here." />
            </div>
          )}
          {busy && <div style={{ marginTop: 16 }}><Spinner label="Economics and Compliance agents are recomputing..." /></div>}
          {err && <div style={{ marginTop: 14 }}><ErrLine onRetry={shock} /></div>}
          {agents && (
            <p className="rise" style={{ marginTop: 14, fontSize: 14.5, lineHeight: 1.65, color: T.text, whiteSpace: "pre-wrap" }}>
              {agents}
            </p>
          )}
        </Panel>
      </div>
    </div>
  );
}

function Row({ k, v, sub, accent, hot }) {
  return (
    <div style={{ background: T.panel, padding: "12px 14px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
      <div>
        <div style={{ fontSize: 13.5, color: accent ? T.gold : T.text, fontWeight: accent ? 600 : 400 }}>{k}</div>
        {sub && <div style={{ fontFamily: "'JetBrains Mono'", fontSize: 11, color: T.muted, marginTop: 2 }}>{sub}</div>}
      </div>
      <div style={{
        fontFamily: "'JetBrains Mono'", fontSize: 15,
        color: accent ? T.gold : hot ? T.shock : T.text, fontWeight: 500,
      }}>{v}</div>
    </div>
  );
}

// ---- layout helpers ----
function Header({ eyebrow, title, sub }) {
  return (
    <div>
      <div style={{ fontFamily: "'JetBrains Mono'", fontSize: 12, color: T.teal, letterSpacing: 0.5, textTransform: "lowercase" }}>{eyebrow}</div>
      <h2 style={{ fontFamily: "'Space Grotesk'", fontWeight: 700, fontSize: 27, color: T.text, margin: "8px 0 6px", lineHeight: 1.2 }}>{title}</h2>
      <p style={{ color: T.muted, fontSize: 15, maxWidth: 720, lineHeight: 1.55, margin: 0 }}>{sub}</p>
    </div>
  );
}
function Label({ children }) {
  return <div style={{ fontFamily: "'JetBrains Mono'", fontSize: 12, color: T.muted, letterSpacing: 0.4 }}>{children}</div>;
}
function Empty({ msg }) {
  return <div style={{ marginTop: 12, color: T.muted, fontSize: 14, lineHeight: 1.5 }}>{msg}</div>;
}
function Continue({ label, onClick }) {
  return (
    <div style={{ display: "flex", justifyContent: "flex-end", marginTop: 4 }}>
      <Btn onClick={onClick}>{label} </Btn>
    </div>
  );
}

// ============================================================
// Shell and stepper
// ============================================================
const STEPS = ["Builder", "Telos match", "Employer", "EESG impact"];

export default function App() {
  const [step, setStep] = useState(0);
  return (
    <div style={{ background: T.ink, minHeight: "100vh", color: T.text, fontFamily: "'Inter', sans-serif" }}>
      <style>{FONTS}</style>
      <div style={{ maxWidth: 1080, margin: "0 auto", padding: "26px 24px 60px" }}>

        {/* brand bar */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", paddingBottom: 18, borderBottom: `1px solid ${T.line}` }}>
          <div style={{ display: "flex", alignItems: "baseline", gap: 12 }}>
            <span style={{ fontFamily: "'Space Grotesk'", fontWeight: 700, fontSize: 22, color: T.text, letterSpacing: 1 }}>FIND</span>
            <span style={{ color: T.muted, fontSize: 13 }}>Africa talent bridge</span>
          </div>
          <span style={{ fontFamily: "'JetBrains Mono'", fontSize: 12, color: T.teal }}>Telos . powered by the CCM</span>
        </div>

        {/* stepper. clickable, so a viewer can move freely */}
        <div style={{ display: "flex", gap: 8, margin: "20px 0 26px", flexWrap: "wrap" }}>
          {STEPS.map((s, i) => {
            const active = i === step, done = i < step;
            return (
              <button key={i} onClick={() => setStep(i)} style={{
                display: "flex", alignItems: "center", gap: 9, cursor: "pointer",
                background: active ? T.panel : "transparent",
                border: `1px solid ${active ? T.gold : T.line}`, borderRadius: 8,
                padding: "9px 13px", color: active ? T.text : T.muted,
                fontFamily: "'Inter'", fontSize: 13.5, fontWeight: active ? 600 : 400,
              }}>
                <span style={{
                  width: 20, height: 20, borderRadius: "50%", fontSize: 11,
                  fontFamily: "'JetBrains Mono'", display: "flex", alignItems: "center", justifyContent: "center",
                  background: done ? T.gold : active ? T.teal : T.panelLite,
                  color: done || active ? T.ink : T.muted,
                }}>{done ? "." : i + 1}</span>
                {s}
              </button>
            );
          })}
        </div>

        {step === 0 && <Candidate onDone={() => setStep(1)} />}
        {step === 1 && <Match onDone={() => setStep(2)} />}
        {step === 2 && <Employer onDone={() => setStep(3)} />}
        {step === 3 && <Impact />}
      </div>
    </div>
  );
}
